output = "tables"
pkgname = "tables"
wipe = true
no-tests = true
add-enum-types = false
no-context = true
add-global-variants = true
no-hooks = true
no-auto-timestamps = true

[mysql]
dbname = "test"
host = "127.0.0.1"
port = "3306"
user = "root"
pass = "123456"
sslmode = "false"

#[[types]]
#[types.match]
#name = "status"
#[types.replace]
#type = "bool"
